version: 2
jobs:
  build:
    
    working_directory: ~/comixed

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: comixed
          paths:
            - ~/.m2
            - java-backend/pom.xml
      
      - run: cd java-backend && mvn dependency:go-offline
      
      - save_cache:
          key: comixed
          paths:
            - ~/.m2
            - java-backend/pom.xml
      
      - run: cd java-backend && mvn clean package
      
      - store_test_results:
          path: java-backend/target/surefire-reports
      
      - store_artifacts:
          path: java-backend/target/comixed-app-0.2.0-SNAPSHOT.jar
